BankTransferTitle="Bank Transfer"
BankTransferDescription = ""
BankTransferIconUrl = ""

CreditDebitCardTitle="Credit / Debit Card"
CreditDebitCardDescription = ""
CreditDebitCardIconUrl = ""

DirectDebitSepaTitle="Direct Debit (SEPA)"
DirectDebitSepaDescription = ""
DirectDebitSepaIconUrl = ""

InvoiceTitle="Invoice"
InvoiceDescription = ""
InvoiceIconUrl = ""

