GrundeinstellungenTab="Paramètres Généraux"
apiUserIdLabel="ID Utilisateur"
apiUserKeyLabel="Clé d'authentification"
spaceIdLabel="ID Espace"
resourceVersionLabel="Version de la Solution"
orderRetryStatusLabel="IDs des Statuts pour les tentatives de paiement ultérieures"
orderRetryStatusTooltip="Permet de définir des statuts de commande qui permettent de sélectionner un autre mode de paiement et de réessayer. Plusieurs statuts peuvent être séparés par un point-virgule &quot; ;&quot;."
refundSuccessfulStatusLabel="Statut ID pour les remboursements réussis"
refundFailedStatusLabel="Statut ID pour les remboursements échoués"
confirmationInvoiceLabel="Autoriser les clients à télécharger la facture"
confirmationPackingSlipLabel="Autoriser les clients à télécharger le bordereau d'expédition"
enablePaymentFetch="Activer la récupération des méthodes de paiement possibles"

BankTransferTab=Bank Transfer
BankTransferActiveLabel=Activé
BankTransferTitleLabel=Titre
BankTransferDescriptionLabel=Description
BankTransferFeeLabel=Frais
BankTransferIconUrlLabel=Url du Symbole (facultatif)
CreditDebitCardTab=Credit / Debit Card
CreditDebitCardActiveLabel=Activé
CreditDebitCardTitleLabel=Titre
CreditDebitCardDescriptionLabel=Description
CreditDebitCardFeeLabel=Frais
CreditDebitCardIconUrlLabel=Url du Symbole (facultatif)
DirectDebitSepaTab=Direct Debit (SEPA)
DirectDebitSepaActiveLabel=Activé
DirectDebitSepaTitleLabel=Titre
DirectDebitSepaDescriptionLabel=Description
DirectDebitSepaFeeLabel=Frais
DirectDebitSepaIconUrlLabel=Url du Symbole (facultatif)
InvoiceTab=Invoice
InvoiceActiveLabel=Activé
InvoiceTitleLabel=Titre
InvoiceDescriptionLabel=Description
InvoiceFeeLabel=Frais
InvoiceIconUrlLabel=Url du Symbole (facultatif)
OnlineBankingTab=Online Banking
OnlineBankingActiveLabel=Activé
OnlineBankingTitleLabel=Titre
OnlineBankingDescriptionLabel=Description
OnlineBankingFeeLabel=Frais
OnlineBankingIconUrlLabel=Url du Symbole (facultatif)
