GrundeinstellungenTab="Grundeinstellungen"
apiUserIdLabel="API Benutzer ID"
apiUserKeyLabel="API Benutzer Key"
spaceIdLabel="Space Id"
resourceVersionLabel="Resource Version"
orderRetryStatusLabel="Status IDs für weitere Bezahlversuche"
orderRetryStatusTooltip="Ermöglicht die Definition von Bestellstatus, die es erlauben, eine andere Zahlungsmethode zu wählen und es erneut zu versuchen. Mehrere Status können durch ein Semikolon &quot;;&quot; voneinander getrennt werden."
refundSuccessfulStatusLabel="Status ID für erfolgreiche Gutschrift"
refundFailedStatusLabel="Status ID für fehlgeschlagene Gutschrift"
confirmationInvoiceLabel="Kunden erlauben, Rechnungsdokument herunterzuladen"
confirmationPackingSlipLabel="Kunden erlauben, Lieferschein herunterzuladen"
enablePaymentFetch="Aktivieren Sie das Abrufen möglicher Zahlungsmethoden"

BankTransferTab=Bank Transfer
BankTransferActiveLabel=Aktiv
BankTransferTitleLabel=Titel
BankTransferDescriptionLabel=Beschreibung
BankTransferFeeLabel=Gebühr
BankTransferIconUrlLabel=Symbol Url (freiwillig)
CreditDebitCardTab=Credit / Debit Card
CreditDebitCardActiveLabel=Aktiv
CreditDebitCardTitleLabel=Titel
CreditDebitCardDescriptionLabel=Beschreibung
CreditDebitCardFeeLabel=Gebühr
CreditDebitCardIconUrlLabel=Symbol Url (freiwillig)
DirectDebitSepaTab=Direct Debit (SEPA)
DirectDebitSepaActiveLabel=Aktiv
DirectDebitSepaTitleLabel=Titel
DirectDebitSepaDescriptionLabel=Beschreibung
DirectDebitSepaFeeLabel=Gebühr
DirectDebitSepaIconUrlLabel=Symbol Url (freiwillig)
InvoiceTab=Invoice
InvoiceActiveLabel=Aktiv
InvoiceTitleLabel=Titel
InvoiceDescriptionLabel=Beschreibung
InvoiceFeeLabel=Gebühr
InvoiceIconUrlLabel=Symbol Url (freiwillig)
OnlineBankingTab=Online Banking
OnlineBankingActiveLabel=Aktiv
OnlineBankingTitleLabel=Titel
OnlineBankingDescriptionLabel=Beschreibung
OnlineBankingFeeLabel=Gebühr
OnlineBankingIconUrlLabel=Symbol Url (freiwillig)
